name: Deploy
env:
  AWS_PROFILE: aquaMM-DEV
  STAGE: DEV

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: build-and-test
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          always-auth: true
          node-version: "14"
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install -g npm@^7
          npm ci

      - name: Deploy
        run: |
          npm run deploy